name: KoiEssentials
main: com.koisv.essentials.Main
version: R1.31-SNAPSHOT
api-version: '1.20'
load: POSTWORLD
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.21
loadbefore:
  - Vault

commands:
  back:
    aliases: ["ㄷ", "b", "뒤로"]
    usage: /<command>
    description: "돌아가"
  hat:
    usage: /<command>
    description: "새 모자"
  ke:
    usage: /<command> reload
    description: "리로드용"
  mem:
    usage: /<command>
    description: "메모리"
  openinv:
    aliases: ["인벤토리"]
    usage: /<command>
    description: "누구세요?"
  spawn:
    aliases: ["넴주", "spawn", "tmvhs"]
    usage: /<command>
    description: "부?활"
  speed:
    aliases: ["속도"]
    usage: /<command>
    description: "SPEEEEEEED"

permissions:
  kes.admin:
    default: op
    description: "ALLL"
    children:
      - kes.spawn
      - kes.spawn.set
      - kes.spawn.others
      - kes.back.others
      - kes.control
      - kes.control.reload
      - kes.gc
      - kes.openinv
      - kes.openinv.*
      - kes.speed
      - kes.speed.others

  kes.spawn:
    default: not op
    description: "SPAWN"
  kes.spawn.set:
    default: op
    description: "Spawn SET"
  kes.spawn.others:
    default: op
    description: "GO SPAWN"

  kes.back:
    default: not op
    description: "BACK"
  kes.back.others:
    default: op
    description: "OTHERBACK"

  kes.hat:
    default: not op
    description: "UwU"

  kes.control:
    default: op
    description: "CONTROL UP"
  kes.control.reload:
    default: op
    description: "RELOADING"

  kes.gc:
    default: op
    description: "BEEP BEEP"

  kes.speed:
    default: op
    description: "SPEEEEEEEEEDDDDDD"
  kes.speed.others:
    default: op
    description: "SPPPPPPPPPPPPPPPED"

  kes.openinv:
    default: not op
    description: "OPENUP"
  kes.openinv.ender:
    default: op
    description: "ENDERRR"
  kes.openinv.others:
    default: op
    description: "OTHERSINV"
  kes.openinv.others.ender:
    default: op
    description: "WHOSIDEAWITHTHIS"