name: KoiEssentials
main: com.koisv.essentials.Main
version: R1.2-SNAPSHOT
api-version: '1.20'
load: POSTWORLD
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - io.github.monun:kommand-core:3.1.6
loadbefore:
  - Vault